import '../model/app_models.dart';

class DemoData {
  static AdminAppState buildState() {
    return AdminAppState(
      students: [
        StudentRecord(
          id: 'STU-104',
          name: 'Amina Rahman',
          mobile: '9847012104',
          fatherName: 'Abdul Rahman',
          motherName: 'Saleena Rahman',
          dateOfBirth: DateTime(2014, 4, 12),
          gender: Gender.female,
          batch: 'Junior Hifz A',
          className: 'Qaida',
          address: 'Vengara, Malappuram',
          guardianName: 'Rahman K.',
          score: 94,
          streak: 18,
          status: RecordStatus.active,
          enrollmentDate: DateTime(2025, 6, 1),
        ),
        StudentRecord(
          id: 'STU-118',
          name: 'Ibrahim Nizar',
          mobile: '9847012118',
          fatherName: 'Nizar P.',
          motherName: 'Fathima Nizar',
          dateOfBirth: DateTime(2013, 9, 3),
          gender: Gender.male,
          batch: 'Junior Hifz B',
          className: 'Nazrah',
          address: 'Tirur, Malappuram',
          guardianName: 'Nizar P.',
          score: 89,
          streak: 11,
          status: RecordStatus.active,
          enrollmentDate: DateTime(2025, 6, 1),
        ),
        StudentRecord(
          id: 'STU-122',
          name: 'Mariam Shifa',
          mobile: '9847012122',
          fatherName: 'Ashraf A.',
          motherName: 'Shifa A.',
          dateOfBirth: DateTime(2012, 1, 22),
          gender: Gender.female,
          batch: 'Senior Moral Science',
          className: 'Hifz',
          address: 'Kondotty, Malappuram',
          guardianName: 'Shifa A.',
          score: 97,
          streak: 24,
          status: RecordStatus.active,
          enrollmentDate: DateTime(2024, 6, 1),
        ),
        StudentRecord(
          id: 'STU-135',
          name: 'Yusuf Sameer',
          mobile: '9847012135',
          fatherName: 'Sameer T.',
          motherName: 'Najma Sameer',
          dateOfBirth: DateTime(2014, 11, 8),
          gender: Gender.male,
          batch: 'Junior Hifz A',
          className: 'Qaida',
          address: 'Manjeri, Malappuram',
          guardianName: 'Sameer T.',
          score: 73,
          streak: 4,
          status: RecordStatus.review,
          enrollmentDate: DateTime(2025, 6, 1),
        ),
      ],
      teachers: [
        TeacherRecord(
          id: 'TCH-11',
          name: 'Usthad Fasal',
          mobile: '9847022011',
          email: 'fasal@alifschool.in',
          qualification: 'Hifz, Bachelor of Islamic Studies',
          subjects: const ['Quran', 'Tajweed'],
          batches: const ['Junior Hifz A', 'Junior Hifz B'],
          status: RecordStatus.active,
        ),
        TeacherRecord(
          id: 'TCH-14',
          name: 'Shameema Ali',
          mobile: '9847022014',
          email: 'shameema@alifschool.in',
          qualification: 'MA Islamic History, B.Ed',
          subjects: const ['Moral Science', 'Akhlaq'],
          batches: const ['Senior Moral Science'],
          status: RecordStatus.active,
        ),
        TeacherRecord(
          id: 'TCH-17',
          name: 'Muhsin Basheer',
          mobile: '9847022017',
          email: 'muhsin@alifschool.in',
          qualification: 'Diploma in Arabic Language',
          subjects: const ['Arabic'],
          batches: const ['Junior Hifz B'],
          status: RecordStatus.active,
        ),
      ],
      batchClasses: [
        BatchClassRecord(
          id: 'BAT-01',
          name: 'Junior Hifz A',
          className: 'Qaida',
          teacherId: 'TCH-11',
          teacherName: 'Usthad Fasal',
          studentCount: 2,
          schedule: 'Mon, Wed, Fri · 7:00 PM',
          capacity: 12,
          status: RecordStatus.active,
        ),
        BatchClassRecord(
          id: 'BAT-02',
          name: 'Junior Hifz B',
          className: 'Nazrah',
          teacherId: 'TCH-17',
          teacherName: 'Muhsin Basheer',
          studentCount: 1,
          schedule: 'Tue, Thu · 7:30 PM',
          capacity: 12,
          status: RecordStatus.active,
        ),
        BatchClassRecord(
          id: 'BAT-03',
          name: 'Senior Moral Science',
          className: 'Hifz',
          teacherId: 'TCH-14',
          teacherName: 'Shameema Ali',
          studentCount: 1,
          schedule: 'Sat, Sun · 9:00 AM',
          capacity: 12,
          status: RecordStatus.active,
        ),
      ],
      activities: [
        ActivityRule(
          id: 'ACT-01',
          name: 'Jamaah Prayer',
          category: 'Prayer',
          points: 10,
          hasQuantity: false,
          isActive: true,
        ),
        ActivityRule(
          id: 'ACT-02',
          name: 'Quran Reading',
          category: 'Quran',
          points: 10,
          hasQuantity: true,
          isActive: true,
        ),
        ActivityRule(
          id: 'ACT-03',
          name: 'Quran Memorization',
          category: 'Quran',
          points: 20,
          hasQuantity: true,
          isActive: true,
        ),
        ActivityRule(
          id: 'ACT-04',
          name: 'Morning Adhkar',
          category: 'Dhikr',
          points: 5,
          hasQuantity: false,
          isActive: true,
        ),
        ActivityRule(
          id: 'ACT-05',
          name: 'Helping Parents',
          category: 'Good Deeds',
          points: 5,
          hasQuantity: false,
          isActive: false,
        ),
      ],
      ratingRules: [
        RatingRule(
          id: 'RATE-01',
          label: 'Excellent',
          minScore: 90,
          maxScore: 100,
          colorName: 'Green',
          isDefault: true,
        ),
        RatingRule(
          id: 'RATE-02',
          label: 'Good',
          minScore: 75,
          maxScore: 89,
          colorName: 'Light Green',
          isDefault: false,
        ),
        RatingRule(
          id: 'RATE-03',
          label: 'Satisfactory',
          minScore: 50,
          maxScore: 74,
          colorName: 'Gold',
          isDefault: false,
        ),
        RatingRule(
          id: 'RATE-04',
          label: 'Needs Improvement',
          minScore: 0,
          maxScore: 49,
          colorName: 'Orange',
          isDefault: false,
        ),
      ],
      reports: [
        ReportSnapshot(
          title: 'Daily participation',
          value: '88%',
          change: '+4.1%',
          trendLabel: 'vs yesterday',
        ),
        ReportSnapshot(
          title: 'Weekly participation',
          value: '92%',
          change: '+6.4%',
          trendLabel: 'vs last week',
        ),
        ReportSnapshot(
          title: 'Average score',
          value: '84',
          change: '+3',
          trendLabel: 'this month',
        ),
        ReportSnapshot(
          title: 'Active students',
          value: '3',
          change: '+1',
          trendLabel: 'this week',
        ),
      ],
      notifications: [
        NotificationCampaign(
          id: 'NTF-01',
          title: 'Weekly progress digest',
          message: 'This week\'s activity summary is ready for your child.',
          audience: 'Parents · All batches',
          scheduledFor: 'Today · 8:30 PM',
          status: CampaignStatus.draft,
        ),
        NotificationCampaign(
          id: 'NTF-02',
          title: 'Badge winners announcement',
          message: 'Congratulations to this week\'s badge earners!',
          audience: 'Students · Senior Moral Science',
          scheduledFor: 'Fri · 7:00 PM',
          status: CampaignStatus.scheduled,
        ),
        NotificationCampaign(
          id: 'NTF-03',
          title: 'Class timing update',
          message: 'Junior Hifz A will move to 7:15 PM from Monday.',
          audience: 'Batch · Junior Hifz A',
          scheduledFor: 'Sent · Mon 6:00 PM',
          status: CampaignStatus.sent,
        ),
      ],
      badges: [
        BadgeDefinition(
          id: 'BDG-01',
          name: 'Consistency Star',
          criteria: '7-day activity streak',
          icon: '⭐',
          bonusPoints: 50,
          recipientCount: 46,
          isActive: true,
        ),
        BadgeDefinition(
          id: 'BDG-02',
          name: 'Monthly Champion',
          criteria: '30-day activity streak',
          icon: '🏆',
          bonusPoints: 200,
          recipientCount: 18,
          isActive: true,
        ),
        BadgeDefinition(
          id: 'BDG-03',
          name: 'Quran Sprint',
          criteria: '50 Quran pages in a week',
          icon: '📖',
          bonusPoints: 100,
          recipientCount: 29,
          isActive: true,
        ),
      ],
      classes: const ['Qaida', 'Nazrah', 'Hifz'],
    );
  }
}
